version: "2.6.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 8919
      POSTGRES_USER: postgres
      POSTGRES_DB: ATL
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  atl_ms:
    image: atl_ms
    depends_on:
      - db
    ports:
      - "4000:4000"